### ISSUE TITLE
Does this work on OSX?

### ISSUE THREAD

**Issue by hirasso** [rozbb/DropboxIgnore#1]
As the question states :) Does your script work on OSX with Perl installed?

**Comment by rozbb** [comment]
This project is completely unmaintained, and I've never tried it on OSX. That being said, I don't see any reason this shouldn't work on OSX with Perl installed. I'd be curious what your results are.

**Comment by sp1thas** [comment]
Hello all, given that:

 1. this project is discontinued
 2. dropbox has introduced [a new way to ignore files](https://help.dropbox.com/files-folders/restore-delete/ignored-files)

I implemented [dropboxignore](https://github.com/sp1thas/dropboxignore), this cross-platform shell script has the minimum dependencies and can be used to ignore/revert files or folders from dropbox. Feel free to give it a try (it is also tested on OSX).

Any feedback is more than welcome.

**Comment by rozbb** [comment]
This looks great! I updated the readme to point to your project
